#!/usr/bin/env python3

import argparse
import sys
import time

parser = argparse.ArgumentParser()
parser.add_argument('--text', default='Banana')
parser.add_argument('--stdout', action='store_true')
parser.add_argument('--stderr', action='store_true')
parser.add_argument('--times', default=1, type=int)
parser.add_argument('--pause', default=0, type=int)
parser.add_argument('--fail', default=False, action='store_true')
args = parser.parse_args()

for i in range(args.times):
    if args.stdout:
        print(args.text)
    if args.stderr:
        print(args.text, file=sys.stderr)
    if args.pause:
        time.sleep(args.pause * 0.001)

if args.fail:
    sys.exit(1)
